"""Create vacation_destinations table with columns

Revision ID: b5735de15ade
Revises: a71b9da8cc0c
Create Date: 2025-05-05 21:50:12.514964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5735de15ade'
down_revision = 'a71b9da8cc0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vacation_destinations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vacation_destinations')
    # ### end Alembic commands ###
